@baseURL = http://localhost:3333
@authToken = {{{{{authenticate.response.body.access_token}}}}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoes@example.com",
  "password": "123456",
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "johndoes@example.com",
  "password": "123456",
}
###

# @name create_question
POST {{baseURL}}/sessions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "How to create a question?",
  "body": "I'm trying to create a question using the API, but I'm not sure how to do it. Can someone help me?"
}

###

@name fetch_recent_questions
GET {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
